

# model params
# encoder:
#   arch: 'resnet18'
#   feature_dim: 1
#   cifar_small_image: True

# decoder:
#   image_shape: [ 3, 32, 32 ]
#   n_channels: 128
#   ch_mults: [ 1, 2, 2, 2 ]
#   is_attn: [ False, True, False, False ]
#   dropout: 0.1
#   n_blocks: 2
#   use_res_for_updown: False
#   z_channels: 146



# model params
# encoder:
#   arch: 'resnet18'
#   feature_dim: 1
#   cifar_small_image: True

# decoder:
#   image_shape: [ 3, 32, 32 ]
#   n_channels: 128
#   ch_mults: [ 1, 2, 2, 2 ]
#   is_attn: [ False, True, False, False ]
#   dropout: 0.1
#   n_blocks: 2
#   use_res_for_updown: False
#   z_channels: 146

diffusion:
  betas: [1.0e-5, 8.0e-3]
  # betas: 'inverted'
  n_T: 1000
  drop_prob: 0.1
  model_input: 43
  model_output: 3
  model_embed: 256
  embed_predict_in : 64
  embed_predict_out: 8
  embed_in: 256
  embed_out: 32


# training params
batch_size: 16
lrate: 1.0e-4
lrate_ratio: 2
optim: 'AdamW'
optim_args:
  weight_decay: 0.05
  betas: [ 0.9, 0.95 ]
grad_clip_norm: 50

n_epoch: 100
warm_epoch: 30
load_epoch: -1
ema: 0.9999

n_sample: 30
save_dir: './reach_chicken'
save_per: 5
dataset: '/home/eai/soda/3D-Diffusion-Policy-master/3D-Diffusion-Policy/data/metaworld_basketball_expert.zarr'